### ISSUE TITLE
Refactor all css

### ISSUE THREAD

**Issue by SirrorsMoore1975** [Phone-Review-App/SakuraSignal#126]
Some css setting are affecting others classes behavior, such as:
```css
/* ReviewCard.css */
span {
   margin: 10px;
}
```
To avoid the css styles colluded with other components and pages, try to give a meaningful name to a particular css. 
- Your Task
- [ ] Refactor css files in the `client/src/styles` folder to avoid colluded styling affecting others components and pages

This issue might have in conjunction with the button css issue in:
- #123
